language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update
  - sudo apt-get install libmagick++-dev libfreetype6-dev libfontconfig1-dev libmagickcore-dev

script:
  - git submodule update -i
  - make
