language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update
  - sudo apt-get install libfreetype6-dev libfontconfig1-dev libpango1.0-dev

script:
  - git submodule update -i --recursive
  - MAGICK_LEGACY=1 MAGICK_MOD=1 bash deploy.sh
