sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

install:
  - sudo add-apt-repository -y ppa:libreoffice/ppa
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update
  - sudo apt-get install -y libfreetype6-dev libfontconfig1-dev libpango1.0-dev librsvg2-dev liblcms2-dev libzip-dev libcdr-dev libicu-dev libcppunit-dev libopencolorio-dev librevenge-dev libboost-all-dev gtk-doc-tools libharfbuzz-dev libselinux1-dev libpoppler-glib-dev
  - sudo rm -rf /usr/include/libcdr* /usr/lib*/*cdr* /usr/lib*/pkgconfig/*cdr*
  - git clone https://github.com/LibreOffice/libcdr
  - cd libcdr
  - sh autogen.sh
  - ./configure --prefix=/usr
  - make -j2
  - sudo make install
  - cd ..
  - git clone https://github.com/ImageMagick/ImageMagick
  - cd ImageMagick
  - git checkout tags/7.0.2-1
  - ./configure --prefix=/usr --disable-docs --disable-deprecated --with-magick-plus-plus=yes --with-quantum-depth=32 --without-dps --without-djvu --without-fftw --without-fpx --without-gslib --without-gvc --without-jbig --without-jpeg --with-lcms --without-openjp2 --without-lqr --without-lzma --without-openexr --without-pango --without-png --without-rsvg --without-tiff --without-webp --without-xml --with-zlib --without-bzlib --enable-static --enable-shared --enable-hdri --with-freetype --without-fontconfig --without-x --without-modules --without-wmf
  - make -j2
  - sudo make install
  - cd ..

script:
  - git submodule update -i --recursive
  - make IM=7 CXXFLAGS_ADD="-DLEGACY"
