sudo: required
dist: trusty

language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo add-apt-repository -y ppa:libreoffice/ppa
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update
  - sudo apt-get install -y libfreetype6-dev libfontconfig1-dev libpango1.0-dev librsvg2-dev liblcms2-dev libzip-dev libcdr-dev libicu-dev libcppunit-dev libopencolorio-dev librevenge-dev libboost-all-dev gtk-doc-tools libharfbuzz-dev libselinux1-dev libpoppler-glib-dev
  - sudo rm -rf /usr/include/libcdr* /usr/lib*/*cdr* /usr/lib*/pkgconfig/*cdr*
  - git clone https://github.com/LibreOffice/libcdr
  - cd libcdr
  - sh autogen.sh
  - ./configure --prefix=/usr
  - make -j2
  - sudo make install
  - cd ..

script:
  - git submodule update -i --recursive
  - NOPNG=1 DEBUG=1 PACKAGE=ReadPDF bash deploy.sh
  - NOPNG=1 TRAVIS=1 DEBUG=1 PACKAGE=Extra bash deploy.sh
  - NOPNG=1 NOPNG=1 DEBUG=1 bash deploy.sh
  - CLEAN=1 MAGICK_OFX=1 NOPNG=1 DEBUG=1 PACKAGE=Magick bash deploy.sh
